### ISSUE TITLE
DRAM segment data does not fit

### ISSUE THREAD

**Issue by belm0** [fededevi/esp_ttgo_pingo_3d#1]
I tried to build for TTGO, but there is an error about static memory use:

```
section `.dram0.bss' will not fit in region `dram0_0_seg'
DRAM segment data does not fit.
region `dram0_0_seg' overflowed by 37168 bytes
```

I tried changing the program in various ways, but strangely the number 37168 is always the same.

**Comment by belm0** [comment]
it may be due to large static buffer like this:
```C
uint16_t copyBuffer[2][DEFAULT_TFT_DISPLAY_HEIGHT][DEFAULT_TFT_DISPLAY_WIDTH];
```

**Comment by fededevi** [comment]
Yeah probably. That buffer is the main framebuffer where the rendering and DMA spi transfers happen. Not sure if your device has less ram or the linker script is different or the screen have higher resolution maybe?

If the problem is the size of that section and not the lack of memory in itself you can try to malloc that buffer.

DEFAULT_TFT_DISPLAY_HEIGHT / WIDTH should be 240 / 135 I think

**Comment by belm0** [comment]
Thank you.  I did eventually malloc the buffer and was able to link and upload, but nothing on the display.

Since TTGO isn't my main device anyway, I'm now focusing on using the memory buffer backend + DMA over SPI.

I noticed that RGB565 isn't actually implemented, so hopefully I'll make some PR's soon.

**Comment by fededevi** [comment]
If I remember correctly I did not implement RGB565 in the graphics library because I did not want to use more memory for buffers. So I rendered in 8 bit and then converted to RGB565 on the fly in the ttgo back-end.
